import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Export data to PDF with table format
 * @param {Array} data - Array of objects to export
 * @param {String} filename - Name of the PDF file
 * @param {String} title - Title of the report
 * @param {Object} options - Additional options (columns, orientation, etc)
 */
export const exportToPDF = (data, filename, title, options = {}) => {
    const {
        columns = null, // Array of {header: 'Name', dataKey: 'name'}
        orientation = 'portrait', // 'portrait' or 'landscape'
        pageSize = 'a4',
        headerInfo = {}, // Additional header info like store name, date range
        footerText = 'Generated by KULA'
    } = options;

    // Create new PDF document
    const doc = new jsPDF({
        orientation,
        unit: 'mm',
        format: pageSize
    });

    // Set font
    doc.setFont('helvetica');

    // Add title
    doc.setFontSize(18);
    doc.setTextColor(40);
    doc.text(title, 14, 20);

    // Add header info
    let yPosition = 30;
    doc.setFontSize(10);
    doc.setTextColor(100);

    if (headerInfo.storeName) {
        doc.text(`Toko: ${headerInfo.storeName}`, 14, yPosition);
        yPosition += 6;
    }

    if (headerInfo.dateRange) {
        doc.text(`Periode: ${headerInfo.dateRange}`, 14, yPosition);
        yPosition += 6;
    }

    if (headerInfo.generatedDate) {
        doc.text(`Tanggal Cetak: ${headerInfo.generatedDate}`, 14, yPosition);
        yPosition += 6;
    }

    yPosition += 5;

    // Prepare table columns
    let tableColumns = columns;
    if (!tableColumns && data.length > 0) {
        // Auto-generate columns from first data object
        tableColumns = Object.keys(data[0]).map(key => ({
            header: key.charAt(0).toUpperCase() + key.slice(1),
            dataKey: key
        }));
    }

    // Prepare table data
    const tableData = data.map(item => {
        const row = {};
        tableColumns.forEach(col => {
            row[col.dataKey] = item[col.dataKey] !== undefined ? item[col.dataKey] : '-';
        });
        return row;
    });

    // Add table
    doc.autoTable({
        startY: yPosition,
        head: [tableColumns.map(col => col.header)],
        body: tableData.map(row => tableColumns.map(col => row[col.dataKey])),
        theme: 'striped',
        headStyles: {
            fillColor: [99, 102, 241], // Indigo color
            textColor: 255,
            fontSize: 10,
            fontStyle: 'bold'
        },
        bodyStyles: {
            fontSize: 9,
            textColor: 50
        },
        alternateRowStyles: {
            fillColor: [245, 247, 250]
        },
        margin: { top: 10, left: 14, right: 14 },
        didDrawPage: (data) => {
            // Footer
            const pageCount = doc.internal.getNumberOfPages();
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();

            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(
                footerText,
                14,
                pageHeight - 10
            );
            doc.text(
                `Halaman ${data.pageNumber} dari ${pageCount}`,
                pageSize.width - 40,
                pageHeight - 10
            );
        }
    });

    // Save PDF
    doc.save(filename);
};

/**
 * Export shift report to PDF
 */
export const exportShiftReportToPDF = (shifts, storeName, dateRange) => {
    const data = shifts.map(shift => ({
        'Kasir': shift.cashier,
        'Mulai': new Date(shift.startTime).toLocaleString('id-ID'),
        'Selesai': shift.endTime ? new Date(shift.endTime).toLocaleString('id-ID') : '-',
        'Modal': `Rp ${shift.initialCash?.toLocaleString() || 0}`,
        'Penjualan': `Rp ${shift.totalSales?.toLocaleString() || 0}`,
        'Tunai': `Rp ${shift.totalCashSales?.toLocaleString() || 0}`,
        'Transfer': `Rp ${shift.totalNonCashSales?.toLocaleString() || 0}`,
        'Status': shift.status === 'active' ? 'Aktif' : 'Selesai'
    }));

    exportToPDF(
        data,
        `Laporan_Shift_${new Date().toISOString().split('T')[0]}.pdf`,
        'Laporan Shift',
        {
            orientation: 'landscape',
            headerInfo: {
                storeName,
                dateRange,
                generatedDate: new Date().toLocaleString('id-ID')
            }
        }
    );
};

/**
 * Export expense report to PDF
 */
export const exportExpenseReportToPDF = (expenses, storeName, dateRange) => {
    const data = expenses.map(exp => ({
        'Tanggal': new Date(exp.date).toLocaleDateString('id-ID'),
        'Waktu': new Date(exp.date).toLocaleTimeString('id-ID'),
        'Kategori': exp.category,
        'Keterangan': exp.reason,
        'Jumlah': `Rp ${Number(exp.amount).toLocaleString()}`,
        'Kasir': exp.cashier || '-'
    }));

    const totalExpense = expenses.reduce((sum, exp) => sum + (Number(exp.amount) || 0), 0);

    exportToPDF(
        data,
        `Laporan_Pengeluaran_${new Date().toISOString().split('T')[0]}.pdf`,
        'Laporan Pengeluaran',
        {
            headerInfo: {
                storeName,
                dateRange,
                generatedDate: new Date().toLocaleString('id-ID')
            },
            footerText: `Total Pengeluaran: Rp ${totalExpense.toLocaleString()} | Generated by KULA`
        }
    );
};

/**
 * Export top selling products to PDF
 */
export const exportTopSellingToPDF = (products, storeName, dateRange) => {
    const data = products.map((product, index) => ({
        'Rank': `#${index + 1}`,
        'Produk': product.name,
        'Kategori': product.category,
        'Qty Terjual': product.totalQuantity.toLocaleString(),
        'Pendapatan': `Rp ${product.totalRevenue.toLocaleString()}`,
        'Profit': `Rp ${product.totalProfit.toLocaleString()}`
    }));

    exportToPDF(
        data,
        `Produk_Terlaris_${new Date().toISOString().split('T')[0]}.pdf`,
        'Laporan Produk Terlaris',
        {
            headerInfo: {
                storeName,
                dateRange,
                generatedDate: new Date().toLocaleString('id-ID')
            }
        }
    );
};
